## Name: Sanyam Goel

# Cosine Simalirities Utility

### Assignment 4

This class calculates cosine similarities on a matrix by pair wise comparion of each row with the next row filling in each index. Since this is a utility class with no attributes, it has classmethods only 

* A matrix required is NxM where N<M
  * In case N>M an exception is raised
  * In case of a zero row an exception is raised
*  The cosines is calculated as follows
    1.    The dot product of each vector is calculated ( by calculating dot product of matrix with its transpose creating a nxn matrix
    2.   The normnal of vector each vector is calculated by row wise multiplication of elements, summing them and finding the square root.
    3.   To find norm of other matrix this 1xn generated array is reshaped into 1xn matrix
    4.   The generated norm is transposed into nx1 matrix and multiplied with 1xn norm
    5.   The two norm matrix are multiplis to form a nxn norm matrix
  *   Divide the matrix of dot products by the matrix of norms this will craete cosine of each index or the cosine similarities matrix

In [12]:
""" Module for cosine simlarities functionality """
from typing import NoReturn, Union
import pdb
import numpy as np
import numpy.typing as npt


class CosineSimaliratiesUtility:

    """
    CosineSimaliratiesUtility This class calculates the
    cosine similarites of a NxM matrix
    It throws an exception in case N>M as required in the exercise
    """
    def __init__(self):

        """
        CosineSimaliratiesUtility constructor

        arguments:

        Due to doc string using 'pass' is cossidered redundant by pylint

        """

    @classmethod
    def calculate_cosine_similarities_matrix(cls,
                                             matrix: npt.NDArray[np.float64]
                                             ) -> Union[npt.NDArray[np.float64],
                                                        NoReturn]:
        """
        CosineSimaliratiesUtility calculate_cosine_similarities_matrix method

            arguments:
                matrix: NxM, of floats

            return:
                np.NDArray[np.float64]: A NxN matrix of cos similarities

            Exceptions:
                In case N>M an exception is thrown as it is required
                in the exercise to calculate cos similarities of M>N

        """

        total_rows, total_columns = matrix.shape

        if cls.__is_dimension_mismatch__(matrix):

            error = f"""Cannot find cosine similarites for a matrix size with
            total rows= {total_rows} and total columns = {total_columns}"""

            raise AssertionError(error)

        if cls.__has_zero_row_in_matrix__(matrix):

            raise AssertionError('Cannot find cosine similarites for a matrix with zero row')

        # pdb.set_trace()

        # Calculates the dividend
        vector_dot_products = np.matmul(matrix,np.transpose(matrix))  
        
        matrix.dot(np.transpose(matrix))

        # Calculate the square of each vector component
        vector_square = np.multiply(matrix, matrix)

        # Calculate the norm of each vector
        vector_normals = np.sqrt(np.sum(vector_square, axis=1)).reshape((1,total_rows))

        # Calculate the transpose of each norm
        vector_normals_transposed = np.transpose(vector_normals)
        
        # Calculate norm matrix
        norms_multiplication = np.dot(vector_normals_transposed, vector_normals)
        
        # Calculate cosine matrix by dividing dot product matrix by norm matrix
        cosine_matrix = np.divide(vector_dot_products,norms_multiplication)

        return cosine_matrix


    @classmethod
    def __has_zero_row_in_matrix__(cls, matrix: npt.NDArray[np.float64]) -> np.bool:

        """
        CosineSimaliratiesUtility __has_zero_row_in_matrix__ method. This method ensures 
        in case there is a zero vector, we do not proceed with cosine similarites calculation 
        as this will case divide by zero exceptions

        Logic:
          Check if a row is zero by checking matrix is zero along axis 1 ( rows)
          This generates an array of True and Flase  1xN.
          Now if we multiply this with a transpose of the same matrix of True and Flase
          i.e, Nx1, this will generate a 1x1 matrix and we can safely return the only element 
          at [0][0]

        arguments:
            matrix: npt.NDArray[np.float64]: matrix of float elements

        return:
            bool: The result if all elemts of a row are  Zero

        """

        total_rows, _ = matrix.shape

        has_zero_vector_matrix = np.any(matrix == 0 , axis = 1).reshape(1, total_rows)

        return has_zero_vector_matrix.dot(np.transpose(has_zero_vector_matrix))[0][0]

    @classmethod
    def __is_dimension_mismatch__(cls, matrix: npt.NDArray[np.float64]) -> npt.bool:

        """
        CosineSimaliratiesUtility __is_dimension_mismatch__ method
        This method validates the dimensions of matrix,
        if number of rows are less than equal to the number of columns or matrix is empty

        arguments:
             matrix: npt.NDArray[np.float64]: matrix of float elements

        return:
            bool: is dimension correct

        """

        total_rows, total_columns = matrix.shape
        
        return total_rows > total_columns or total_rows == 0 or total_columns == 0


 ## Test case 1:
    Random matrix of size 4x4

In [13]:
random_float_matrix = np.random.random_sample((4,4))

print(f'Selected Random float matrix:\n {random_float_matrix}\n')

try:
    
    calculated_cosine_similarities = CosineSimaliratiesUtility.calculate_cosine_similarities_matrix(random_float_matrix)
    print(f'Generated Cosine similarities matrix:\n {calculated_cosine_similarities}\n')
    
except Exception as e:
    
    print(e)

Selected Random float matrix:
 [[0.59872211 0.58414494 0.49875167 0.87909737]
 [0.34583103 0.38190994 0.11540994 0.50210126]
 [0.16205354 0.27749122 0.6682717  0.88202233]
 [0.25002814 0.06354962 0.97231945 0.31491535]]

[[1.31196756 0.72861474 1.15230776 1.05410123]]
[[1.31196756]
 [0.72861474]
 [1.15230776]
 [1.05410123]]
[[1.72125888 0.9559189  1.5117904  1.38294662]
 [0.9559189  0.53087944 0.83958842 0.76803369]
 [1.5117904  0.83958842 1.32781317 1.21464903]
 [1.38294662 0.76803369 1.21464903 1.11112941]]
Generated Cosine similarities matrix:
 [[1.         0.97194881 0.90475853 0.68593158]
 [0.97194881 1.         0.81231411 0.49616632]
 [0.90475853 0.81231411 1.         0.81150054]
 [0.68593158 0.49616632 0.81150054 1.        ]]



 ## Test case 2:
    Random matrix of size 5x6

In [4]:
random_float_matrix = np.random.random_sample((5,6))
print(f'Selected Random float matrix:\n {random_float_matrix}\n')

try:
    
    calculated_cosine_similarities = CosineSimaliratiesUtility.calculate_cosine_similarities_matrix(random_float_matrix)
    print(f'Generated Cosine similarities matrix:\n {calculated_cosine_similarities}\n')
    
except Exception as e:
    
    print(e)

Selected Random float matrix:
 [[0.51088934 0.70873459 0.62708759 0.04164356 0.93353657 0.02740726]
 [0.18175527 0.10380747 0.1209641  0.59255214 0.86133299 0.71835553]
 [0.98452149 0.16225925 0.17000027 0.04173454 0.74190707 0.4117102 ]
 [0.9638774  0.28033588 0.96342727 0.48508329 0.16627018 0.6021068 ]
 [0.92894491 0.9223773  0.59044356 0.13805616 0.68468948 0.40426177]]

Generated Cosine similarities matrix:
 [[1.         0.59276518 0.75953666 0.65212499 0.91787385]
 [0.59276518 1.         0.68909642 0.57291601 0.61017853]
 [0.75953666 0.68909642 1.         0.73278554 0.84747117]
 [0.65212499 0.57291601 0.73278554 1.         0.81438842]
 [0.91787385 0.61017853 0.84747117 0.81438842 1.        ]]



 ## Test case 3:
    Zero row matrix

In [5]:
random_float_matrix = np.array([[1.0,2.0,3.0],[0.,0.,0.],[12.4,2,56.0]])
print(f'Selected zero row float matrix:\n {random_float_matrix}\n')

try:
    
    calculated_cosine_similarities = CosineSimaliratiesUtility.calculate_cosine_similarities_matrix(random_float_matrix)
    print(f'Generated Cosine similarities matrix:\n {calculated_cosine_similarities}\n')
    
except Exception as e:
    
    print(e)


Selected zero row float matrix:
 [[ 1.   2.   3. ]
 [ 0.   0.   0. ]
 [12.4  2.  56. ]]

Cannot find cosine similarites for a matrix with zero row


 ## Test case 4:
    Empty matrix

In [6]:
random_float_matrix = np.array([[],[]])
print(f'Selected zero row float matrix:\n {random_float_matrix}\n')

try:
    
    calculated_cosine_similarities = CosineSimaliratiesUtility.calculate_cosine_similarities_matrix(random_float_matrix)
    print(f'Generated Cosine similarities matrix:\n {calculated_cosine_similarities}\n')
    
except Exception as e:
    
    print(e)


Selected zero row float matrix:
 []

Cannot find cosine similarites for a matrix size with
            total rows= 2 and total columns = 0


 ## Test case 5:
    Random matrix 30x30

In [7]:
random_float_matrix = np.random.random_sample((10,30))
print('Selected Random float matrix:\n {matrix}\n'.format(matrix=random_float_matrix))

try:
    
    calculated_cosine_similarities = CosineSimaliratiesUtility.calculate_cosine_similarities_matrix(random_float_matrix)
    print(f'Generated Cosine similarities matrix:\n {calculated_cosine_similarities}\n')
    
except Exception as e:
    
    print(e)

Selected Random float matrix:
 [[0.98173664 0.50237822 0.70368094 0.73429138 0.30563703 0.40039019
  0.91316524 0.28753351 0.02900422 0.98847664 0.40223562 0.10470016
  0.98235422 0.66396948 0.39182847 0.98721589 0.03606201 0.24799339
  0.61925138 0.70835523 0.32768156 0.61990446 0.03868438 0.8218846
  0.80709955 0.33647549 0.26975545 0.89325505 0.18025483 0.51553537]
 [0.48294606 0.29472727 0.25851468 0.01395838 0.18394824 0.20573943
  0.40919621 0.20827459 0.35469143 0.63271346 0.96887133 0.07482271
  0.14178004 0.09712403 0.73743854 0.87512549 0.39412353 0.44702375
  0.03073085 0.08063079 0.2810436  0.40503628 0.60304722 0.06334917
  0.68412177 0.90335494 0.73010665 0.81567765 0.1635184  0.3056016 ]
 [0.9525617  0.86474351 0.10219931 0.61873199 0.17749266 0.52324657
  0.90146807 0.45234617 0.82627227 0.14889554 0.80928373 0.14522999
  0.98177366 0.43595015 0.0471982  0.89243288 0.47855366 0.75484367
  0.05719173 0.74309435 0.16382404 0.73251476 0.66106108 0.72688615
  0.10796913 0.0